Initial architecture and layout header
Paris22/react-stickers-shop pull request #1
Opened 2022-06-23 13:03 UTC by Paris22

-initial architecture
-layout header
-stylized header

2022-06-24 06:50 UTC, ShDanil requested changes

2022-06-24 06:50 UTC, ShDanil commented on src/App.js
> +        <Route exact path="/basket" element={<Basket/>}/>
Не basker, а cart

2022-06-24 06:50 UTC, ShDanil commented on src/App.js
> +        <Route exact path="/logs" element={<Logs/>}/>
Так же на будущее, роуты чаще всего выносят в константы. Можешь сейчас не править, а как дойдут руки

2022-06-24 06:50 UTC, ShDanil commented on src/Basket/Basket.js
> +
Пустой див тож лучше не оставляй. Ечлм в некст пре будет, то коммент оставь.

2022-06-24 06:50 UTC, ShDanil commented on src/Configs/Global.styled.js
> +    background: rgb(190,242,245);
Цвета сразу в конфиг цветов, иначе после будешь по 100 раз переиспользовать

2022-06-24 06:50 UTC, ShDanil commented on src/Configs/Global.styled.js
> +    background: radial-gradient(circle, rgba(190,242,245,1) 0%, rgba(238,251,248,1) 100%);
Тут не обязательно в конфиг , просто всю строку

2022-06-24 06:50 UTC, ShDanil commented on src/Configs/Global.styled.js
> +    box-sizing: border-box;
Сделай это обнуление дефолтно для всех элементов через *{}

2022-06-24 06:50 UTC, ShDanil commented on src/Configs/Global.styled.js
> +    box-sizing: border-box;
Имел в виду падинг, маржин и бокс-сайзинг

2022-06-24 06:50 UTC, ShDanil commented on src/Header/Header.js
> +                        <Button>Sort Price</Button>
Sort by

2022-06-24 06:50 UTC, ShDanil commented on src/Header/Header.js
> +                <TotalAmount>
Не совсем понял что значит order count?

2022-06-24 06:50 UTC, ShDanil commented on src/Header/Header.styled.js
> +  background: rgba(250,255,0,1);
В конфиг

2022-06-24 06:50 UTC, ShDanil commented on src/Header/Header.styled.js
> +  display: flex;
В двльнейшем будет много таких компонентов у которых дисплей флекс и центр. Можешь сделать унтверсальный компонент и его переиспользовать.

2022-06-24 06:50 UTC, ShDanil commented on src/Header/Header.styled.js
> +  display: flex;
А лучше еще чтобы он мог пропс принимать.
По дефолту флекс, и через пропс центр и направление. Тебе полезно будет

2022-06-24 06:50 UTC, ShDanil commented on src/Header/Header.styled.js
> +
Три одинаковых. Сделай один на все

2022-06-25 08:06 UTC, Paris22 commented on src/App.js
> +        <Route exact path="/logs" element={<Logs/>}/>
имеешь ввиду прям полностью <Route exact path="/" element={<MainPage/>}/> в константу?

2022-06-25 08:07 UTC, Paris22 commented on src/Configs/Global.styled.js
> +    background: rgb(190,242,245);
Отдельно сделать конфиг для цветов? Или как?

2022-06-25 08:07 UTC, Paris22 commented on src/Configs/Global.styled.js
> +    background: radial-gradient(circle, rgba(190,242,245,1) 0%, rgba(238,251,248,1) 100%);
Всм всю строку?

2022-06-25 08:09 UTC, Paris22 commented on src/Header/Header.js
> +                <TotalAmount>
Кол-во товаров в корзине или кол-во заказов можно так сказать

2022-06-25 08:20 UTC, Paris22 commented on src/Basket/Basket.js
> +
Почему не оставлять?

2022-06-25 08:35 UTC, ShDanil commented on src/App.js
> +        <Route exact path="/logs" element={<Logs/>}/>
Нет, только строки по типу "/cart"

2022-06-25 08:36 UTC, ShDanil commented on src/Basket/Basket.js
> +
Ну, вообще, не надо вливать не рабочий код. А так будет непонятно для ревьюера.

2022-06-25 08:37 UTC, ShDanil commented on src/Configs/Global.styled.js
> +    background: rgb(190,242,245);
Да, файл, где в объекте будут цвета и после использовать только из них.
Ну или строковые константы

2022-06-25 08:38 UTC, ShDanil commented on src/Configs/Global.styled.js
> +    background: radial-gradient(circle, rgba(190,242,245,1) 0%, rgba(238,251,248,1) 100%);
Все значение цвета

2022-06-25 08:39 UTC, ShDanil commented on src/Header/Header.js
> +                <TotalAmount>
Total in cart лучше, имхо

2022-06-26 08:29 UTC, Paris22 commented on src/App.js
> +        <Route exact path="/basket" element={<Basket/>}/>
Сделал

2022-06-26 08:34 UTC, Paris22 commented on src/App.js
> +        <Route exact path="/logs" element={<Logs/>}/>
Сделал

2022-06-26 08:34 UTC, Paris22 commented on src/Basket/Basket.js
> +
Сделал

2022-06-26 09:27 UTC, Paris22 commented on src/Configs/Global.styled.js
> +    box-sizing: border-box;
Сделал

2022-06-28 18:12 UTC, closed without merging